# Generated by Django 4.2.16 on 2024-11-24 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('duration', models.IntegerField(help_text='duration in months')),
            ],
        ),
    ]
